# Generated by Django 2.0.6 on 2019-02-21 16:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lecture2App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('age', models.IntegerField(default=0)),
                ('birthday', models.DateField(default=datetime.datetime(2019, 2, 21, 16, 50, 4, 402164, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='chair',
            name='purchaseTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 16, 50, 4, 394000, tzinfo=utc)),
        ),
    ]
